openapi: '3.0.0'

servers:
  - url: 'https://api.haskoin.com/bch/'
  - url: 'https://api.haskoin.com/btc/'
  - url: 'https://api.haskoin.com/bchtest/'
  - url: 'https://api.haskoin.com/btctest/'

info:
  version: '0.23.4'
  title: Blockchain API
  contact:
    name: Jean-Pierre Rupp
    url: https://github.com/haskoin/haskoin-store
    email: jprupp@protonmail.ch
  license:
    name: Unlicense
    url: http://unlicense.org/

tags:
  - name: Address
  - name: Transaction
  - name: Block
  - name: Network

paths:
  '/health':
    get:
      tags:
        - Network
      summary: Node health status.
      operationId: healthCheck
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '503':
          description: unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheck'
              example:
                headers:
                  height: 1283593
                  hash: '00000000000003ad033d7508575ea8f8fd4d9d5d331a9ecd22ab712bdbc35dbb'
                blocks:
                  height: 0
                  hash: '000000000933ea01ad0ee984209779baaec3ced90fa3f408719526f8d77f4943'
                peers: 0
                net: bchtest
                ok: false
                synced: false
                version: '0.1.2'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/address/{address}/transactions':
    get:
      tags:
        - Address
      summary: Transactions relevant to an address.
      operationId: getAddressTxs
      parameters:
        - $ref: '#/components/parameters/addressParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: List of transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockTx'
                example:
                  - txid: '128d3979e1837631688d54a5e55716d44617ef70da1237042abcea51128d4ae2'
                    block:
                      height: 1283392
                      position: 1
                  - txid: '5d53eb8a24d02f7b92825ff1b2b68f478c9b0129e8bbc90e9a893b461086c6b7'
                    block:
                      height: 1283391
                      position: 1
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid address provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/address/{address}/transactions/full':
    get:
      tags:
        - Address
      summary: Full transactions relevant to an address.
      operationId: getAddressTxsFull
      parameters:
        - $ref: '#/components/parameters/addressParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: List of transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid address provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/transactions':
    get:
      tags:
        - Address
      summary: Transactions relevant to multiple addresses.
      operationId: getMultipleAddressTxs
      parameters:
        - $ref: '#/components/parameters/addressesParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: List of full transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockTx'
                example:
                  - txid: '128d3979e1837631688d54a5e55716d44617ef70da1237042abcea51128d4ae2'
                    block:
                      height: 1283392
                      position: 1
                  - txid: '5d53eb8a24d02f7b92825ff1b2b68f478c9b0129e8bbc90e9a893b461086c6b7'
                    block:
                      height: 1283391
                      position: 1
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid address provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/transactions/full':
    get:
      tags:
        - Address
      summary: Full transactions relevant to multiple addresses.
      operationId: getMultipleAddressTxsFull
      parameters:
        - $ref: '#/components/parameters/addressesParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: List of full transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid address provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/{address}/balance':
    get:
      tags:
        - Address
      operationId: getBalance
      summary: Balance and transaction counts for an address.
      parameters:
        - $ref: '#/components/parameters/addressParam'
      responses:
        '200':
          description: >
            Address balance.
            Will return data for unknown but valid addresses.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Balance'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid address provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/balances':
    get:
      tags:
        - Address
      summary: Balance and transaction counts for multiple addresses.
      operationId: getMultipleAddressBalances
      parameters:
        - $ref: '#/components/parameters/addressesParam'
      responses:
        '200':
          description: >
            List of balances for every valid address provided.
            Will return data for unknown but valid addresses.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Balance'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid Address Provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/{address}/unspent':
    get:
      tags:
        - Address
      summary: Unspent outputs for an address.
      operationId: getAddressUnspent
      parameters:
        - $ref: '#/components/parameters/addressParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/offsetParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: List of unspent outputs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unspent'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid address provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/address/unspent':
    get:
      tags:
        - Address
      summary: Unspent outputs for multiple addresses.
      operationId: getMultipleAddressUnspent
      parameters:
        - $ref: '#/components/parameters/addressesParam'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: List of unspent outputs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Unspent'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Invalid address provided.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/best':
    get:
      tags:
        - Block
      summary: Head of block chain.
      operationId: getBlockHead
      parameters:
        - $ref: '#/components/parameters/notxParam'
      responses:
        '200':
          description: Best block data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/best/raw':
    get:
      tags:
        - Block
      summary: Raw head of block chain.
      operationId: getRawBlockHead
      responses:
        '200':
          description: Best raw block.
          content:
            application/json:
              schema:
                type: string
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/latest':
    get:
      tags:
        - Block
      summary: Latest nodes of block chain.
      operationId: getLatestBlocks
      parameters:
        - $ref: '#/components/parameters/notxParam'
      responses:
        '200':
          description: List of contiguous blocks up to block chain head.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/block/{block}':
    get:
      tags:
        - Block
      operationId: getBlock
      summary: Information about a block.
      parameters:
        - $ref: '#/components/parameters/notxParam'
        - $ref: '#/components/parameters/blockParam'
      responses:
        '200':
          description: Block data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Block not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/block/{block}/raw':
    get:
      tags:
        - Block
      operationId: getRawBlock
      summary: Raw block data.
      parameters:
        - $ref: '#/components/parameters/blockParam'
      responses:
        '200':
          description: Block data.
          content:
            application/json:
              schema:
                type: string
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Block not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/blocks':
    get:
      tags:
        - Block
      operationId: getBlocks
      summary: Information about multiple blocks.
      parameters:
        - $ref: '#/components/parameters/notxParam'
        - $ref: '#/components/parameters/blocksParam'
      responses:
        '200':
          description: >
            List of block data objects.
            If a block is not found it will not be on the list.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/height/{height}':
    get:
      tags:
        - Block
      operationId: getBlocksAtHeight
      summary: Blocks at specific height.
      parameters:
        - $ref: '#/components/parameters/blockHeightParam'
        - $ref: '#/components/parameters/notxParam'
      responses:
        '200':
          description: >
            List of block data objects at specified height.
            First one in list is on the main block chain.
            If height is beyond block chain head the list will be empty.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/height/{height}/raw':
    get:
      tags:
        - Block
      operationId: getRawBlocksAtHeight
      summary: Raw blocks at specific height.
      parameters:
        - $ref: '#/components/parameters/blockHeightParam'
      responses:
        '200':
          description: >
            List of block data objects at specified height.
            First one in list is on the main block chain.
            If height is beyond block chain head the list will be empty.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/time/{time}':
    get:
      tags:
        - Block
      operationId: getBlocksAtTime
      summary: Blocks at or before unix timestamp.
      parameters:
        - $ref: '#/components/parameters/timeParam'
        - $ref: '#/components/parameters/notxParam'
      responses:
        '200':
          description: >
            Last block mined at or before the specified unix timestamp.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/time/{time}/raw':
    get:
      tags:
        - Block
      operationId: getRawBlocksAtTime
      summary: Raw block at or before unix timestamp.
      parameters:
        - $ref: '#/components/parameters/timeParam'
      responses:
        '200':
          description: >
            Last block mined at or before the specified unix timestamp.
          content:
            application/json:
              schema:
                type: string
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/block/heights':
    get:
      tags:
        - Block
      operationId: getBlocksAtHeights
      summary: Blocks at specific heights.
      parameters:
        - $ref: '#/components/parameters/blockHeightsParam'
        - $ref: '#/components/parameters/notxParam'
      responses:
        '200':
          description: >
            List of block data objects at heights provided.
            First block returned at each height is on the main chain.
            If a provided height is beyond the block chain head there
            will be no blocks at that height in the list.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockData'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transaction/{txid}':
    get:
      tags:
        - Transaction
      operationId: getTransaction
      summary: Transaction information.
      parameters:
        - $ref: '#/components/parameters/txidParam'
      responses:
        '200':
          description: Transaction object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Transaction not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transaction/{txid}/raw':
    get:
      tags:
        - Transaction
      operationId: getRawTransaction
      summary: Transaction encoded in network binary format.
      parameters:
        - $ref: '#/components/parameters/txidParam'
      responses:
        '200':
          description: Binary transaction encoded as a hex JSON string.
          content:
            application/json:
              schema:
                type: string
                example: '01000000017795e2e9960d5aaf8bd679521e1928a0ade0c8ac4d0c2b1d8529c5be5e68b75f000000006b483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006cfeffffff02481f3d00000000001976a914151a5bd62929872630531213391c3e2952fa069c88ac00000000000000002c6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c3000000000'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Transaction not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/evict':
    get:
      tags:
        - Address
      operationId: evictXPub
      summary: Evict extended public key from cache
      parameters:
        - $ref: '#/components/parameters/xpubParam'
      responses:
        '200':
          description: Returns true if the xpub was in the cache prior to eviction
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    type: boolean
                    example: true
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transaction/{txid}/after/{height}':
    get:
      tags:
        - Transaction
      operationId: cbAfterHeight
      summary: Transaction spends coins created after height.
      parameters:
        - $ref: '#/components/parameters/txidParam'
        - $ref: '#/components/parameters/blockHeightParam'
      responses:
        '200':
          description: >
            Returns whether the given transaction has a coinbase ancestor beyond the specified height.
            If an internal recursion limit is reached, the response will be `null`.
          content:
            application/json:
              schema:
                type: object
                required:
                  - result
                properties:
                  result:
                    type: boolean
                    nullable: true
                    example: true
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/transactions':
    get:
      tags:
        - Transaction
      operationId: getTransactions
      summary: Multiple transaction information.
      parameters:
        - $ref: '#/components/parameters/txidsParam'
      responses:
        '200':
          description: >
            List of transaction information objects.
            If a transaction is not found, it will not appear in the list.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary

    post:
      tags:
        - Transaction
      operationId: postTransaction
      requestBody:
        description: Publish a transaction to the peer-to-peer network.
        content:
          text/plain:
            schema:
              type: string
              description: Hex-encoded transaction.
              example: '01000000017795e2e9960d5aaf8bd679521e1928a0ade0c8ac4d0c2b1d8529c5be5e68b75f000000006b483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006cfeffffff02481f3d00000000001976a914151a5bd62929872630531213391c3e2952fa069c88ac00000000000000002c6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c3000000000'
          application/octet-stream:
            schema:
              type: string
              format: binary
              description: Binary transaction encoded in network-specific format.
      responses:
        '200':
          description: Transaction published.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TxId'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Transaction rejected.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

        '500':
          description: >
            This error is returned if:



            * No network peers are connected to node at the time.

            * Timeout was reached while publishing. This is most likely a silent rejection.

            * Selected network peer disconnected while publishing transaction.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transactions/block/{block}':
    get:
      tags:
        - Transaction
        - Block
      operationId: getBlockTransactions
      summary: Block transaction data.
      parameters:
        - $ref: '#/components/parameters/blockParam'
      responses:
        '200':
          description: List of transaction objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Block not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transactions/block/{block}/raw':
    get:
      tags:
        - Transaction
        - Block
      operationId: getRawBlockTransactions
      summary: Block transactions encoded in network binary format.
      parameters:
        - $ref: '#/components/parameters/blockParam'
      responses:
        '200':
          description: List of transaction objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: '01000000017795e2e9960d5aaf8bd679521e1928a0ade0c8ac4d0c2b1d8529c5be5e68b75f000000006b483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006cfeffffff02481f3d00000000001976a914151a5bd62929872630531213391c3e2952fa069c88ac00000000000000002c6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c3000000000'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '404':
          description: Block not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/transactions/raw':
    get:
      tags:
        - Transaction
      operationId: getRawTransactions
      summary: Transactions encoded in network binary format.
      parameters:
        - $ref: '#/components/parameters/txidsParam'
      responses:
        '200':
          description: >
            List of transaction objects.
            If a transaction is not found it will not be in the list.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: '01000000017795e2e9960d5aaf8bd679521e1928a0ade0c8ac4d0c2b1d8529c5be5e68b75f000000006b483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006cfeffffff02481f3d00000000001976a914151a5bd62929872630531213391c3e2952fa069c88ac00000000000000002c6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c3000000000'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/mempool':
    get:
      tags:
        - Transaction
      operationId: getMempool
      summary: Mempool transactions.
      responses:
        '200':
          description: List of transaction identifiers from mempool.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - '8198a7924b0c4cc5d1b71e48b4f28e5106d2d536181d018acecb6e9f7ebce689'
                  - 'eed4160b9919901e7f55a93d5e9f1add5c7e56c930276532673105844c233b3f'
                  - 'cdb3793bb6c2669e01da5e8751d8975766c81fbce7bd9d7d08414b84448d3129'
                  - '870d7515f9ab782f7b84d3bf15d40e801b835d4abc5389f522d29e5ace223de9'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/events':
    get:
      tags:
        - Block
        - Transaction
      operationId: getEventStream
      summary: Live stream of imported transactions and blocks.
      responses:
        '200':
          description: Stream of event objects.
          content:
            application/x-json-stream:
              schema:
                $ref: '#/components/schemas/Event'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/peers':
    get:
      tags:
        - Network
      operationId: getPeers
      summary: Connected network peers.
      responses:
        '200':
          description: List of peer objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Peer'
                example:
                  - useragent: '/Bitcoin ABC:0.18.5(EB32.0)/'
                    address: '34.245.216.80:18333'
                    version: 70015
                    services: '0000000000000025'
                    relay: true
                  - useragent: '/Bitcoin SV:0.1.0(EB128.0)/'
                    address: '142.93.42.82:18333'
                    version: 70015
                    services: '0000000000000025'
                    relay: true
            application/octet-stream:
              schema:
                type: string
                format: binary
                
  '/xpub/{xpub}':
    get:
      tags:
        - Address
      operationId: getXPubSummary
      summary: Extended public key aggregate balance and transactions.
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/xpubDerive'
        - $ref: '#/components/parameters/nocacheParam'
      responses:
        '200':
          description: Summary object for extended public key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/XPubSummary'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Extended public key invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/transactions/full':
    get:
      tags:
        - Address
      operationId: getXPubTransactionsFull
      summary: Transaction data relevant to an extended public key.
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/xpubDerive'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/nocacheParam'
      responses:
        '200':
          description: List of transaction objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Extended public key invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/transactions':
    get:
      tags:
        - Address
      operationId: getXPubTransactions
      summary: Transactions relevant to an extended public key.
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/xpubDerive'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/nocacheParam'
      responses:
        '200':
          description: List of transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BlockTx'
                example:
                  - block:
                      height: 765798
                      position: 6
                    txid: '534fedf9caf3323e4a08f17d813199a0b3f561b1c9d58ad4a50278a611e8a45d'
                  - block:
                      height: 765798
                      position: 5
                    txid: 'be45116b6f505a4d5d8fb17cfe12678f70e9ac2df003aae1ce89c37cbc034384'
                  - block:
                      height: 765798
                      position: 4
                    txid: '14288fc7465fa8c786fd19e31d163688ced5d66636e9f761b4e8e376f2421492'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Extended public key invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/balances':
    get:
      tags:
        - Address
      operationId: getXPubBalances
      summary: Extended public key balances.
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/xpubDerive'
        - $ref: '#/components/parameters/nocacheParam'
      responses:
        '200':
          description: List of address balances for extended public key provided.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/XPubBalance'
                example:
                  - path: [1,8]
                    balance:
                      received: 199880000
                      utxo: 0
                      address: 'bchtest:qrmaylmr0t7ad0sg80nwdfw2ft5ysn3hccvhk5rp89'
                      txs: 2
                      unconfirmed: 0
                      confirmed: 0
                  - path: [1,9]
                    balance:
                      received: 199770000
                      utxo: 0
                      address: 'bchtest:qrta9zrumx2x9xlkj3ecxurpkv0zspv9xy7tlreccv'
                      txs: 2
                      unconfirmed: 0
                      confirmed: 0
                  - path: [1,10]
                    balance:
                      received: 199770000
                      utxo: 0
                      address: 'bchtest:qquvk7vrffk7m76x24tnr572mjpykghhg5fjptsjs6'
                      txs: 2
                      unconfirmed: 0
                      confirmed: 0
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Extended public key invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary

  '/xpub/{xpub}/unspent':
    get:
      tags:
        - Address
      operationId: getXPubUnspent
      summary: Unspent outputs from extended public key.
      parameters:
        - $ref: '#/components/parameters/xpubParam'
        - $ref: '#/components/parameters/xpubDerive'
        - $ref: '#/components/parameters/heightParam'
        - $ref: '#/components/parameters/limitParam'
        - $ref: '#/components/parameters/nocacheParam'
      responses:
        '200':
          description: List of unspent outputs.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/XPubUnspent'
                example:
                  - path: [0,1959]
                    unspent:
                      pkscript: '76a914a7ec2ca3345ebe30c265bab1f4bbfb0e7716727288ac'
                      value: 1000000
                      address: 'bchtest:qzn7ct9rx30tuvxzvkatra9mlv88w9njwg0p0gqkjv'
                      block:
                        height: 1096570
                        position: 9
                      index: 0
                      txid: '717c7732a6e30c7a06b3c0f5eac040878d6e6f91e17c2471d38eb28050af8cac'
                  - path: [0,1792]
                    unspent:
                      pkscript: '76a91472dbe14842d2e6d7da1c03e81012a9835c6c646488ac'
                      value: 10000
                      address: 'bchtest:qpedhc2ggtfwd476rsp7syqj4xp4cmryvs98s3w6u2'
                      block:
                        height: 1092503
                        position: 12
                      index: 1
                      txid: '2733fcd7d55f5f7696e18f1eaaa5f9970cd88e063af4775e4139f1eb5482a856'
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Extended public key invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/octet-stream:
              schema:
                type: string
                format: binary
                
                
                
components:
  schemas:
  
    BlockRef:
      oneOf:
        - $ref: '#/components/schemas/Block'
        - $ref: '#/components/schemas/Mempool'
      example:
        mempool: 1548766186903

    Block:
      type: object
      required:
        - height
        - position
      properties:
        height:
          description: Block height.
          type: integer
          example: 1283393
        position:
          description: Position of transaction within block.
          type: integer
          example: 2

    Mempool:
      type: object
      required:
        - mempool
      properties:
        mempool:
          description: Time when transaction was accepted in mempool.
          type: integer
          format: int64
          example: 1548766187

    XPubBalance:
      type: object
      required:
        - path
        - balance
      properties:
        path:
          $ref: '#/components/schemas/XPubPath'
        balance:
          $ref: '#/components/schemas/Balance'

    XPubPath:
      type: array
      description: Extended public key derivation path for an address.
      items:
        type: integer
      example: [1, 10]

    XPubUnspent:
      type: object
      required:
        - path
        - unspent
      properties:
        path:
          $ref: '#/components/schemas/XPubPath'
        unspent:
          $ref: '#/components/schemas/Unspent'

    XPubSummary:
      type: object
      required:
        - balance
        - indices
        - paths
      properties:
        balance:
          type: object
          description: Aggregate balance for all addresses in extended public key.
          required:
            - confirmed
            - unconfirmed
            - received
            - utxo
          properties:
            confirmed:
              description: Confirmed balance for all addresses in extended public key.
              type: integer
            unconfirmed:
              description: Mempool balance for all addresses in extended public key.
              type: integer
            received:
              description: >
                Total received on external addresses.



                Note: this number may be smaller than the total confirmed plus
                unconfirmed if an address from the change chain has been used to
                receive funds from an external source.
              type: integer
            utxo:
              description: Number of unconfirmed transaction outputs.
              type: integer
        indices:
          type: object
          description: >
            Highest derivation indices found for provided extended public key.
            See: [BIP-44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)
          required:
            - external
            - change
          properties:
            external:
              type: integer
            change:
              type: integer
        paths:
          type: object
          description: >
            Addresses and corresponding paths for returned transactions.
          additionalProperties:
            type: array
            items:
              type: integer
          example:
            'bchtest:qrmaylmr0t7ad0sg80nwdfw2ft5ysn3hccvhk5rp89': [1, 8]
            'bchtest:qrta9zrumx2x9xlkj3ecxurpkv0zspv9xy7tlreccv': [1, 9]
            'bchtest:qquvk7vrffk7m76x24tnr572mjpykghhg5fjptsjs6': [1, 10]

    BlockTx:
      type: object
      description: Information about a transaction and its place in the block chain.
      required:
        - block
        - txid
      properties:
        block:
          $ref: '#/components/schemas/BlockRef'
        txid:
          type: string
          example: '534fedf9caf3323e4a08f17d813199a0b3f561b1c9d58ad4a50278a611e8a45d'

    Balance:
      type: object
      required:
        - address
        - confirmed
        - unconfirmed
        - utxo
        - received
        - txs
      properties:
        address:
          type: string
          example: 'bchtest:qrr724dvaz5kdhujv52urdrwv0hy4jxpusgspun650'
        confirmed:
          type: integer
          format: int64
          description: Sum of confirmed unspent output values.
          example: 0
        unconfirmed:
          type: integer
          format: int64
          description: Sum of unconfirmed unspent output values.
          example: 0
        utxo:
          description: Total number of unspent outputs.
          type: integer
          format: int64
          example: 0
        received:
          description: Total received by this address, including spent.
          type: integer
          format: int64
          example: 4013201
        txs:
          description: Number of transactions affecting this address balance.
          type: integer
          format: int64
          example: 2

    Unspent:
      type: object
      description: Information about unspent output.
      required:
        - address
        - block
        - txid
        - index
        - pkscript
        - value
      properties:
        address:
          type: string
          nullable: true
          example: 'qq235k7k9y5cwf3s2vfpxwgu8c5497sxnsdnxv6upc'
        block:
          $ref: '#/components/schemas/BlockRef'
        txid:
          type: string
          example: '0d5764c89d3fbf8bea9b329ad5e0ddb6047e72313c0f7b54dcb14f4d242da64b'
        index:
          type: integer
          example: 0
        pkscript:
          type: string
          example: '76a914151a5bd62929872630531213391c3e2952fa069c88ac'
        value:
          type: integer
          format: int64
          description: Value in satoshi.
          example: 4005704

    BlockData:
      type: object
      required:
        - hash
        - height
        - mainchain
        - previous
        - time
        - version
        - bits
        - nonce
        - size
        - tx
        - merkle
        - subsidy
        - fees
        - outputs
      properties:
        hash:
          type: string
          example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'
        size:
          type: integer
          description: >
            Raw size of a block, including witness data.
            This is not a virtual size and does not perform segwit discount calculations.
          example: 722
        height:
          type: integer
          example: 1283393
        mainchain:
          type: boolean
          description: Block is the block chain head or an ancestor. It has not been orphaned.
          example: true
        previous:
          type: string
          example: '000000000000024005a247066be86876777cd84f5bbbc21ba02d32e7822c2fb9'
        time:
          type: integer
          format: int64
          example: 1548766137
        version:
          type: integer
          format: int64
          example: 536870912
        bits:
          type: integer
          format: int64
          example: 437016577
        nonce:
          type: integer
          format: int64
          example: 12019207
        tx:
          type: array
          example:
            - '17106222f0c49ff2553e0fe39966d6fbd08b1d5ea3ef5b2359d94a69846b50fc'
            - '5fb7685ebec529851d2b0c4dacc8e0ada028191e5279d68baf5a0d96e9e29577'
            - 'ce0b0d3ac21b91f24b5b0fc8f057071656496aa898fa7ee01f6b1f7d9b169a9a'
          items:
            type: string
        merkle:
          type: string
          example: '76999ce20135a02df2d7a7a78282fd748b8804b76a817a25ced05f1cf4f2d2a5'
        subsidy:
          type: integer
          format: int64
          description: Total block subsidy in satoshi.
          example: 78125000
        fees:
          type: integer
          format: int64
          description: Total transaction fees in satoshi.
          example: 115499
        outputs:
          type: integer
          format: int64
          description: Total outputs from this block, including spent.
          example: 470103316006
        weight:
          type: integer
          description: SegWit block weight.

    Input:
      type: object
      required:
        - coinbase
        - txid
        - output
        - sigscript
        - sequence
        - pkscript
        - value
        - address
      properties:
        coinbase:
          type: boolean
          example: false
        txid:
          type: string
          example: '5fb7685ebec529851d2b0c4dacc8e0ada028191e5279d68baf5a0d96e9e29577'
        output:
          type: integer
          example: 0
        sigscript:
          type: string
          example: '483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006c'
        value:
          type: integer
          format: int64
          nullable: true
          example: 4008203
        sequence:
          type: integer
          format: int64
          example: 4294967294
        address:
          type: string
          nullable: true
          example: 'bchtest:qzyrvsm6z4ucrhaq4zza3wylre7mavvldgr67jrxt4'
        pkscript:
          type: string
          nullable: true
          example: '76a9148836437a157981dfa0a885d8b89f1e7dbeb19f6a88ac'
        witness:
          description: Witness Data.
          type: array
          example: []
          items:
            type: string

    Spender:
      type: object
      description: Reference to a transaction input.
      required:
        - txid
        - input
      properties:
        txid:
          type: string
          example: '5fb7685ebec529851d2b0c4dacc8e0ada028191e5279d68baf5a0d96e9e29577'
        input:
          type: integer
          example: 0

    Output:
      type: object
      description: Transactiotn Output data.
      required:
        - address
        - pkscript
        - value
        - spent
      properties:
        address:
          type: string
          nullable: true
          example: 'bchtest:qzy3e4pnrglcd3ump5ndqrwu5qv2j8szcv6extyerq'
        pkscript:
          type: string
          example: '76a914891cd4331a3f86c79b0d26d00ddca018a91e02c388ac'
        value:
          type: integer
          format: int64
          example: 4010702
        spent:
          type: boolean
          example: true
        spender:
          $ref: '#/components/schemas/Spender'

    Transaction:
      type: object
      description: Detailed transaction information.
      required:
        - txid
        - size
        - version
        - locktime
        - fee
        - inputs
        - outputs
        - block
        - deleted
        - time
      properties:
        txid:
          type: string
          example: '0d5764c89d3fbf8bea9b329ad5e0ddb6047e72313c0f7b54dcb14f4d242da64b'
        size:
          type: integer
          description: >
            Raw transaction size including witness data but excluding SegWit discount calculations.
          example: 245
        version:
          type: integer
          format: int64
          example: 1
        locktime:
          type: integer
          format: int64
          example: 0
        fee:
          type: integer
          format: int64
          example: 2499
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/Input'
          example:
            - pkscript: '76a9148836437a157981dfa0a885d8b89f1e7dbeb19f6a88ac'
              value: 4008203 
              address: 'bchtest:qzyrvsm6z4ucrhaq4zza3wylre7mavvldgr67jrxt4'
              sequence: 4294967294
              output: 0
              sigscript: '483045022100bb913689120d3b0c15a4cbf8692db56b280fce590d6742c0786eb9e86adafeff022057eb92814fa417349a867aa38b8a7c38a12c72ae6fa3b479b2e477c5a4482898412103d740fe05c374c9ffdc294d6d486b4b490db9322124cafbd56fee3a71cb9c006c'
              coinbase: false
              txid: '5fb7685ebec529851d2b0c4dacc8e0ada028191e5279d68baf5a0d96e9e29577'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/Output'
          example:
            - spent: true
              pkscript: '76a914151a5bd62929872630531213391c3e2952fa069c88ac'
              value: 4005704
              address: 'bchtest:qq235k7k9y5cwf3s2vfpxwgu8c5497sxnsdnxv6upc'
              spender:
                input: 0
                txid: 'f1173bb9269c5f7da1e188fae7b6295f3ed4d2861fbd45f4b5415f5bbe06d8ae'
            - spent: false
              pkscript: '6a09696e7465726c696e6b2094112b9aec1d3e1e7c397d40330c920677f74966c858f5ccf940bdb43c580c30'
              value: 0
              address: null
        block:
          $ref: '#/components/schemas/BlockRef'
        deleted:
          type: boolean
          description: This transaction is no longer considered valid.
          example: false
        time:
          type: integer
          format: int64
          example: 1548767230
        rbf:
          type: boolean
          example: false
          description: Unconfirmed transaction vulnerable to replace-by-fee attack.
        weight:
          type: integer
          example: 980
          description: SegWit transaction weight.

    Event:
      type: object
      required:
        - type
        - id
      properties:
        type:
          type: string
          enum:
            - tx
            - block
          example: block
        id:
          type: string
          description: Block or transaction identifier
          example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'

    Peer:
      type: object
      required:
        - useragent
        - address
        - version
        - services
        - relay
      properties:
        useragent:
          type: string
          example: '/Bitcoin ABC:0.18.4(EB32.0)/'
        address:
          type: string
          example: '34.253.51.235:18333'
        version:
          type: integer
          example: 70015
        services:
          type: string
          example: '0000000000000025'
        relay:
          type: boolean
          description: This peer relays transactions.
          example: true

    HealthCheck:
      type: object
      required:
        - headers
        - blocks
        - peers
        - net
        - ok
        - synced
        - version
      properties:
        headers:
          type: object
          description: Information about block chain headers.
          required:
            - hash
            - height
          properties:
            hash:
              type: string
              nullable: true
              example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'
            height:
              type: integer
              nullable: true
              example: 1283393
        blocks:
          type: object
          description: Information about indexed full blocks.
          required:
            - hash
            - height
          properties:
            hash:
              type: string
              nullable: true
              example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'
            height:
              type: integer
              nullable: true
              example: 1283393
        peers:
          type: integer
          description: Number of connected peers.
          nullable: true
          example: 20
        net:
          type: string
          description: Network to which this node is connected.
          example: bchtest
        ok:
          type: boolean
          description: Node is in good health.
          example: true
        synced:
          type: boolean
          description: Block chain is fully indexed.
          example: true
        version:
          type: string
          example: '0.1.2'

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    TxId:
      type: object
      required:
        - txid
      properties:
        txid:
          type: string
          example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'

  parameters:

    addressParam:
      name: address
      in: path
      required: true
      schema:
        type: string
        example: 'qrr724dvaz5kdhujv52urdrwv0hy4jxpusgspun650'

    addressesParam:
      name: addresses
      in: query
      explode: false
      required: true
      schema:
        type: array
        items:
          type: string
          example: 'qrr724dvaz5kdhujv52urdrwv0hy4jxpusgspun650'

    limitParam:
      name: limit
      in: query
      required: false
      schema:
        type: integer
      description: Maximum number of entries to return.

    heightParam:
      name: height
      in: query
      required: false
      schema:
        type: integer
      description: >
        * If a block height is specified, only elements at or below that
        height on the block chain are returned.

        * If a block hash is specified, only entries at or below that block
        are returned.

        * If a transaction id is specified, only entries at on below that
        transaction's relative position on the blockchain are returned.

        * If a unix timestamp is specified, return transactions that were
        received (mempool) or confirmed (block chain) at or before that
        time.
    offsetParam:
      name: offset
      in: query
      required: false
      schema:
        type: integer
      description: >
        Skip this many entries from the beginning of the result set.

    nocacheParam:
      name: nocache
      in: query
      required: false
      schema:
        type: boolean
      description: Do not use the cache to retrieve this data

    notxParam:
      name: notx
      in: query
      required: false
      schema:
        type: boolean
      description: Do not include block transaction identifiers except for the coinbase.

    blockParam:
      name: block
      in: path
      required: true
      schema:
        type: string
      example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'

    blocksParam:
      name: blocks
      in: path
      explode: false
      required: true
      schema:
        type: array
        items:
          type: string
          example: '000000000000069cc8b7d9cb759a59f754692d9cb5b4e4b7a9dba37c57ab65e8'

    blockHeightParam:
      name: height
      in: path
      required: true
      schema:
        type: integer
        example: 1283393

    blockHeightsParam:
      name: heights
      in: query
      explode: false
      required: true
      schema:
        type: array
        example:
          - 1283393
        items:
          type: integer

    txidParam:
      name: txid
      in: path
      required: true
      schema:
        type: string
        example: '0d5764c89d3fbf8bea9b329ad5e0ddb6047e72313c0f7b54dcb14f4d242da64b'

    timeParam:
      name: time
      in: path
      required: true
      schema:
        type: integer
        example: 1575994134

    txidsParam:
      name: txids
      in: query
      explode: false
      required: true
      schema:
        type: array
        items:
          type: string
          example: '0d5764c89d3fbf8bea9b329ad5e0ddb6047e72313c0f7b54dcb14f4d242da64b'

    xpubParam:
      name: xpub
      in: path
      required: true
      schema:
        type: string
        example: tpubD8XsNAGEy3Pzeeq6hmbRjwrP7G6Goobw4jWvu68tKzxDSFE5VmgpKoDeSFjnmgCLPrijuQwHVodUv7oZDqPNJbzC4mxZStZisGAEwgbpccH

    xpubDerive:
      name: derive
      in: query
      required: false
      schema:
        type: string
        enum: [segwit, compat, standard]
      description: >
        Use `segwit` for P2WPKH addresses, `compat` for P2SH-P2WPKH
        backwards-compatible addresses, or `standard` for regular non-SegWit
        addresses. Has no effect on non-SegWit networks (i.e. Bitcoin Cash).
